### ISSUE TITLE
Email d'invitació a la plataforma per admins

### ISSUE THREAD

**Issue by microstudi** [Som-Energia/decidim-som-energia-app#46]
Enviar text d'invitacio diferent depent de si la persona invitada es al CAS o externa.

#### Tasks
- [x]  Add testing environment
- [x] Redirect CAS users to cas login upon accepting invitation

**Comment by paarals** [comment]
![imatge](https://user-images.githubusercontent.com/40388743/110928804-93b4e080-8327-11eb-80be-bbd590f4d423.png)
