### ISSUE TITLE
Confirm that you want to desjoin from the meeting

### ISSUE THREAD

**Issue by paarals** [Som-Energia/decidim-som-energia-app#81]
**La teva sol·licitud de nova funcionalitat està relacionada amb un problema?**
In the process of registering the meeting in Decidim, a button is generated where the user has the option to join. If you click the same button again, the user desjoin from the meeting. Because only one click is required, users sometimes inadvertently withdraw their registration.

**Descriu la solució que desitges**

If the user clicks the "Going" button a pop up will be displayed asking the user to confirm their action. See the video: 
https://user-images.githubusercontent.com/40388743/116985050-44a67e80-accc-11eb-8fc6-57cb024bc8d2.mp4

**Descriu alternatives que hagis considerat**
Open :)

**Context addicional**
This process reinforces the real intentionality of the user and avoids unwanted actions.

**Aquest problema podria afectar les dades privades dels usuaris?**
Nop

https://meta.decidim.org/processes/roadmap/f/122/proposals/16340

**Comment by paarals** [comment]
>Also, the button label is not very understandable right now, it just says "Joined". The person does not understand that clicking that will cancel their registration.

>I would suggest changing the button label to "Cancel your registration" or something along those lines to make it more understandable. Above the button, there can be the text "You have signed up for this meeting".

**Comment by aitorlb** [comment]
https://github.com/decidim/decidim/pull/7970
